trajectory_follower:
  ros__parameters:
    odom_topic: "/pf/pose/odom"
    drive_topic: "/vesc/high_level/input/nav_0"
    
    lookahead: 5.0
    speed: 4.0
    wheelbase: 0.3302

    lane_width: 0.5
    lane_buffer: 0.1